---
name: 'Delete PR preview'
description: 'Composite action to delete PR preview'

runs:
  using: "composite"
  steps:
    - name: Define PR version
      shell: sh
      run: echo ::set-output name=PR_VERSION::"PR-${{ github.event.number }}"
      id: vars

    - name: Delete ${{ steps.vars.outputs.PR_VERSION }} preview
      shell: sh
      run: |
        rm -Rf "${{ steps.vars.outputs.PR_VERSION }}"

    - name: Commit and push to gh-pages
      shell: sh
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git commit -am "Automated deletion"
        git push

    - name: Remove comment to preview doc link
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: ${{ steps.vars.outputs.PR_VERSION }}
        delete: true

