---
name: 'Build and publish stable doc'
description: 'Composite action to build and publish stable doc site'
inputs:
  AWS_ACCESS_KEY_ID:
    description: 'AWS secrets id'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS secrets key'
    required: true

runs:
  using: "composite"
  steps:
    - name: set environment vars from .env file
      uses: c-py/action-dotenv-to-setenv@v2
      with:
        env-file: '.env'

    - name: Isolate TAG
      shell: sh
      run: echo ::set-output name=TAG::"${GITHUB_REF#refs/*/}"

    - name: DEBUG
      run: |
        echo "${GITHUB_REF}"
        echo "${GITHUB_REF#refs/*/}"
      shell: sh

    - name: Build doc
      uses: ./common/.github/actions/build
      with:
        VERSION: ${{ steps.vars.outputs.TAG }}

    - name: Publish ${{ env.STABLE_VERSION }} to AWS
      uses: ./common/.github/actions/publish-aws
      with:
        VERSION: ${{ env.STABLE_VERSION }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}

    - name: Publish ${{ steps.vars.outputs.TAG }} to AWS
      uses: ./common/.github/actions/publish-aws
      with:
        VERSION: ${{ steps.vars.outputs.TAG }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
