---
name: 'validate links'
description: 'Composite action to validate links'

runs:
  using: "composite"
  steps:
    - name: Test links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: yes
        use-verbose-mode: yes
        check-modified-files-only: yes
        base-branch: main
        config-file: ./common/config/link-check.json
