name: 'Publish to AWS'
description: 'Composite action to publish site to AWS'
inputs:
  VERSION:
    description: 'name for version to publish'
    required: true
    default: 'latest'
  AWS_ACCESS_KEY_ID:
    description: 'AWS secrets id'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS secrets key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload [${{ env.LANGUAGE }}] ${{ inputs.VERSION }} to ${{ env.AWS_S3_BUCKET }} S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET  }}
        AWS_REGION: ${{ env.AWS_REGION }}
        SOURCE_DIR: ${{ env.SOURCE_DIR }}
        DEST_DIR: ${{ env.PROJECT }}/${{ env.LANGUAGE }}/${{ inputs.VERSION }}/
