---
name: Validate Katacoda scenarios

on: [push, pull_request]

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Katacoda CLI
        run: sudo npm i katacoda-cli --global
      - name: Validate Katacoda scenarios
        run: find . -iname 'katacoda*' -type d -exec sh -c 'echo $1 | katacoda scenarios:validate' shell {} \;
