---
name: Validate Katacoda scenarios

on: [push]

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Katacoda CLI
        run: |
          sudo npm i katacoda-cli --global
      - name: Validate Katacoda scenarios
        run: |
          echo "${{ github.workspace }}/katacoda-preview-doc" | katacoda scenarios:validate
