---
name: Test the links

on: [pull_request]

jobs:
  links-check:
    name: Check links
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Links check
        uses: ConsenSys/doctools.action-builder/actions/tests/links@main
