---
name: Delete PR preview

on:
  pull_request_target:
    types: [closed]

jobs:
  deploy:
    name: Remove PR preview from pages
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout code from repos'
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Delete PR preview
        uses: ./common/.github/actions/publish-pr-close
