name: Publish latest on AWS S3 bucket

# Controls when the action will run.
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'checkout code from repos'
        with:
          fetch-depth: 0

      # TODO move this env step in docker image
      - uses: c-py/action-dotenv-to-setenv@v2
        name: 'set environment vars from .env file'
        with:
          env-file: '.env'

      # TODO move this env step in docker image
      - uses: vafinvr/template-env-action@master
        name: 'replace values with env vars in mkdocs.yml'
        with:
          filename: 'mkdocs.yml'

      - uses: NicolasMassart/doctool-action-builder@main
        name: "Build doc for [${{ env.LANGUAGE }}] ${{ env.LATEST_VERSION }}"

      - uses: jakejarvis/s3-sync-action@master
        name: 'Upload ${{ env.LANGUAGE }}/${{ env.LATEST_VERSION }} to AWS'
        with:
          args: '--acl public-read --follow-symlinks --delete'
        env:
          AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          SOURCE_DIR: ${{ env.SOURCE_DIR }}
          DEST_DIR: "${{ env.PROJECT }}/${{ env.LANGUAGE }}/${{ env.LATEST_VERSION }}/"
