---
name: Publish PR on GH Pages

# Controls when the action will run.
on: [ push ]

env:
  PR_LABEL: PR-${{ github.event.number }}

jobs:
  deploy:
    name: Build and publish PR preview
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout code from repos'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'set environment vars from .env file'
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: '.env'

      - name: "Build doc for [${{ env.LANGUAGE }}] ${{ env.LATEST_VERSION }}"
        uses: ConsenSys/doctools.action-builder@main

      - name: Deploy Preview
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: site # The folder the action should deploy.
          target-folder: ${{ env.PR_LABEL }}
          commit-message: Preview for ${{ env.PR_LABEL }}
          single-commit: true

