---
name: Publish stable and tag on AWS S3 bucket

on:
  release:
    types: [published]
    branches: [main]

jobs:
  deploy:
    name: Build and publish released site
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Set output
        run: echo ::set-output name=tag::"${GITHUB_REF#refs/*/}"
        id: vars

      - name: checkout code from repos
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for mkdocs to be able to display pages last update info

      - name: Build doc
        uses: ./common/.github/actions/build
        with:
          version: ${{ env.LATEST_VERSION }}

      - name: Publish ${{ env.STABLE_VERSION }} to AWS
        uses: ./common/.github/actions/publish-aws
        with:
          version: ${{ env.STABLE_VERSION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Publish ${{ steps.vars.outputs.tag }} to AWS
        uses: ./common/.github/actions/publish-aws
        with:
          version: ${{ steps.vars.outputs.tag }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
