---
name: Publish stable and tag on AWS S3 bucket

# Controls when the action will run.
# Trigger the workflow on release activity
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Build and publish released site
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        run: "echo ::set-output name=tag::${GITHUB_REF#refs/*/}"
        id: vars

      - name: checkout code from repos
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set environment vars from .env file
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: '.env'

      - name: Build doc for [${{ env.LANGUAGE }}] ${{ env.LATEST_VERSION }}
        uses: ConsenSys/doctools.action-builder@main

      - name: Upload [${{ env.LANGUAGE }}] ${{ env.STABLE_VERSION }} to ${{ env.AWS_S3_BUCKET }} S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          SOURCE_DIR: ${{ env.SOURCE_DIR }}
          DEST_DIR: ${{ env.PROJECT }}/${{ env.LANGUAGE }}/${{ env.STABLE_VERSION }}/

      - name: Upload [${{ env.LANGUAGE }}] ${{ steps.vars.outputs.tag }}to ${{ env.AWS_S3_BUCKET }} S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          SOURCE_DIR: ${{ env.SOURCE_DIR }}
          DEST_DIR: ${{ env.PROJECT }}/${{ env.LANGUAGE }}/${{ steps.vars.outputs.tag }}/
