---
name: Publish stable and tag on AWS S3 bucket

on:
  workflow_run:
    workflows:
      - "Validate Katacoda scenarios"
      - "Check links in changed Markdown files"
      - "Lint Code Base"
    types:
      - completed

jobs:
  deploy:
    name: Build and publish released site
    runs-on: ubuntu-latest
    # Trigger the job on release activity only and when other tests are done
    if: github.event.repository.fork == false && github.event.type == 'published' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Set output
        run: echo ::set-output name=tag::"${GITHUB_REF#refs/*/}"
        id: vars

      - name: checkout code from repos
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set environment vars from .env file
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: '.env'

      - name: Build doc for [${{ env.LANGUAGE }}] ${{ env.LATEST_VERSION }}
        uses: ConsenSys/doctools.action-builder@main

      - name: Publish to AWS
        uses: ./.github/actions/publish-aws
        with:
          version: ${{ env.STABLE_VERSION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Publish to AWS
        uses: ./.github/actions/publish-aws
        with:
          version: ${{ steps.vars.outputs.tag }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
