---
name: Test spelling and guidelines

# TODO configure and move to common actions

on: [pull_request]

env:
  CONFIG: /docs/.github/vale/.vale.ini

jobs:
  spelling:
    name: Vale
    runs-on: ubuntu-latest
    environment: no-secret
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Sync styles
        run: |
          docker run --rm \
                       -v $(pwd):/docs \
                       -w /docs \
                       jdkato/vale --config $CONFIG sync
      - name: Run Vale check
        run: |
          docker run --rm \
                       -v $(pwd):/docs \
                       -w /docs \
                       jdkato/vale --config $CONFIG --glob='!docs/assets/*' ./docs/
