---
name: Test the doc

on: [push, pull_request]

jobs:
  katacoda:
    name: Validate Katacoda scenarios
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Katacoda
        uses: ./common/.github/actions/katacoda

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint code
        uses: ./common/.github/actions/lint
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  links-check:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Links check
        uses: ./common/.github/actions/links
