---
name: Check links in changed Markdown files

on: [push]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: yes
          use-verbose-mode: yes
          check-modified-files-only: yes
          base-branch: main
